spring.application.name=KinalRestApplication

#Conexion MySQL
spring.datasource.url = jdbc:mysql://localhost:3306/dbClientes_in5av?createDatabaseIfNotExist=true
spring.datasource.username = IN5AV
spring.datasource.password = !+admin5av
server.port= 8041

#JPA / hibernate
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true